### ISSUE TITLE
Error: RPC_CONNECTION_TIMEOUT

### ISSUE THREAD

**Issue by Almoullim** [amiralies/coc-discord#1]
Running NeoVim v0.4.3 on Windows 10

it works most of the time but sometimes it suddenly keep giving me this error

```
[coc.nvim] error: UnhandledRejection: Error: RPC_CONNECTION_TIMEOUT
```

**Comment by amiralies** [comment]
This happens when the connection to discord rpc can not be establishd, (I.E when discord is not running). 
I think a better error message should be shown and a command to retry
