### ISSUE TITLE
Detect NeoVim or Vim

### ISSUE THREAD

**Issue by frogamic** [amiralies/coc-discord#8]
I am using this with vim but it shows as NeoVim in Discord, would be nice if it could detect and show the appropriate logo for vim in discord. Otherwise great plugin, shocked at how easy it was to set up.

**Comment by amiralies** [comment]
Thank you for the feedback.
I think it should show Vim on discord whether you are using neovim or vim. It's the application name on discord dev portal.
Maybe you're using another fork. anyway, you can create your own application with your desired name on discord dev portal and change [clientId](https://github.com/amiralies/coc-discord/blob/master/src/index.ts#L7) to use that
